modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="fishnsteak"
version="1.0.0"
displayName="Jadeanthium"
displayURL="https://modrinth.com/project/fishnsteak"
logoFile="logo.png"
credits="made by xdec, compiled by mcreator"
authors="xdec"
description="dont assume this mod has any effort put in it"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.fishnsteak]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fishnsteak]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration